POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço",
    "description": "Alguma descrição",
    "price": 1400,
    "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/65983fcfbf5606d9d393e2b8

###
DELETE http://localhost:3000/api/services/65983fcfbf5606d9d393e2b8

###
PUT http://localhost:3000/api/services/65983fcfbf5606d9d393e2b8
Content-Type: application/json

{
    "name": "TESTE DE ATUALIZAÇÃO",
    "description": "Alguma descrição 2",
    "price": 2500,
    "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu evento",
    "author": "Fanaina ",
    "description": "Uma festa de aniversário",
    "budget": 9000,
    "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "Alguma descrição",
            "price": 1400,
            "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        {
            "name": "Algum serviço 2",
            "description": "Alguma descrição",
            "price": 3000,
            "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },
        {
            "name": "Algum serviço 3",
            "description": "Alguma descrição",
            "price": 3400,
            "image": "https://images.unsplash.com/photo-1704358434054-a4cf8fa4cc2a?q=80&w=1887&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}

###
GET http://localhost:3000/api/parties

###
GET http://localhost:3000/api/parties/65983fcfbf5606d9d393e2b8
