Algoritmo "EMPREGO"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2023
Var
// Seção de Declarações das variáveis 
salario: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o salário: ")
leia(salário)

se(salario <= 2000)
 entao
escreva ("Candidato selecionado para a primeira fase da condicional simples")

fimse
Fimalgoritmo