Algoritmo "organizar_gavetas"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2023
Var
// Seção de Declarações das variáveis 
g1, g2, g3 : caracter
obj1, obj2, obj3   : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
g1 <- "Meias"
g2 <- "Camisetas"
g3 <- "Gravatas"

obj1 <- 12
obj2 <- 20
obj3 <- 6

Fimalgoritmo